[package]
name = "mongo"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.0.0"
chrono = "0.4"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
futures-util = "0.3"
colored = "2.0"
